#!/usr/bin/env python3
"""Embed engine/shaders/*.glsl into engine/src/shaders_gen/*.h as
C++ raw-string literals.

Regenerate with:  python3 tools/embed_shaders.py
Runs automatically from CMakeLists.txt and build_wasm.{ps1,sh,bat}.

Runtime behavior is unchanged: generated headers define the same
`static const char* k...` variables, still loaded via LoadShaderFromMemory.
Edit the .glsl files, never the generated headers.
"""
import sys
from pathlib import Path

ENGINE = Path(__file__).resolve().parent.parent
SHADERS = ENGINE / "shaders"
GEN = ENGINE / "src" / "shaders_gen"

# glsl file -> (generated header, variable name)
MAPPING = {
    "water_web.vs": ("water_web_vs.h", "kWaterVS"),
    "water_web.fs": ("water_web_fs.h", "kWaterFS"),
    "water_desktop.vs": ("water_desktop_vs.h", "kWaterVS"),
    "water_desktop.fs": ("water_desktop_fs.h", "kWaterFS"),
    "sky_web.vs": ("sky_web_vs.h", "kSkyVS"),
    "sky_web.fs": ("sky_web_fs.h", "kSkyFS"),
    "sky_desktop.vs": ("sky_desktop_vs.h", "kSkyVS"),
    "sky_desktop.fs": ("sky_desktop_fs.h", "kSkyFS"),
    "terrain_web.vs": ("terrain_web_vs.h", "kTerrainVS"),
    "terrain_web.fs": ("terrain_web_fs.h", "kTerrainFS"),
    "terrain_desktop.vs": ("terrain_desktop_vs.h", "kTerrainVS"),
    "terrain_desktop.fs": ("terrain_desktop_fs.h", "kTerrainFS"),
    "clouds_web.vs": ("clouds_web_vs.h", "kCloudRaymarchVS"),
    "clouds_web.fs": ("clouds_web_fs.h", "kCloudRaymarchFS"),
    "clouds_desktop.vs": ("clouds_desktop_vs.h", "kCloudRaymarchVS"),
    "clouds_desktop.fs": ("clouds_desktop_fs.h", "kCloudRaymarchFS"),
    "plane_web.vs": ("plane_web_vs.h", "kPlaneVS"),
    "plane_web.fs": ("plane_web_fs.h", "kPlaneFS"),
    "plane_desktop.vs": ("plane_desktop_vs.h", "kPlaneVS"),
    "plane_desktop.fs": ("plane_desktop_fs.h", "kPlaneFS"),
    "seabed_web.vs": ("seabed_web_vs.h", "kSeabedVS"),
    "seabed_web.fs": ("seabed_web_fs.h", "kSeabedFS"),
    "seabed_desktop.vs": ("seabed_desktop_vs.h", "kSeabedVS"),
    "seabed_desktop.fs": ("seabed_desktop_fs.h", "kSeabedFS"),
}


def pick_delim(src: str) -> str:
    delim = "DW_SHADER"
    while f"){delim}\"" in src:
        delim += "_"
    return delim


def main() -> int:
    GEN.mkdir(parents=True, exist_ok=True)
    missing = [n for n in MAPPING if not (SHADERS / n).is_file()]
    if missing:
        print(f"ERROR: missing shader sources: {missing}")
        return 1
    for glsl_name, (header_name, var) in MAPPING.items():
        src = (SHADERS / glsl_name).read_text(encoding="utf-8")
        delim = pick_delim(src)
        # NOTE: no newline after '(' — '#version' must stay on line 1 or
        # WebGL/ANGLE rejects the shader ("#version must occur on first line").
        header = (
            "// GENERATED by tools/embed_shaders.py — do not edit.\n"
            f"// Source: shaders/{glsl_name}\n"
            "// Regenerate: python3 tools/embed_shaders.py\n"
            "#pragma once\n\n"
            f"static const char* {var} = R\"{delim}({src}){delim}\";\n"
        )
        (GEN / header_name).write_text(header, encoding="utf-8", newline="\n")
        print(f"generated src/shaders_gen/{header_name}")
    print(f"OK: {len(MAPPING)} headers generated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
