// GENERATED by tools/embed_shaders.py — do not edit.
// Source: shaders/plane_desktop.vs
// Regenerate: python3 tools/embed_shaders.py
#pragma once

static const char* kPlaneVS = R"DW_SHADER(#version 330
in vec3 vertexPosition;
in vec2 vertexTexCoord;
in vec3 vertexNormal;
uniform mat4 mvp;
out vec2 fragTexCoord;
out vec3 fragNormal;
void main() {
    fragTexCoord = vertexTexCoord;
    fragNormal = vertexNormal;
    gl_Position = mvp * vec4(vertexPosition, 1.0);
}
)DW_SHADER";
