// GENERATED by tools/embed_shaders.py — do not edit.
// Source: shaders/plane_web.vs
// Regenerate: python3 tools/embed_shaders.py
#pragma once

static const char* kPlaneVS = R"DW_SHADER(attribute vec3 vertexPosition;
attribute vec2 vertexTexCoord;
attribute vec3 vertexNormal;
uniform mat4 mvp;
varying vec2 fragTexCoord;
varying vec3 fragNormal;
void main() {
    fragTexCoord = vertexTexCoord;
    fragNormal = vertexNormal;
    gl_Position = mvp * vec4(vertexPosition, 1.0);
}
)DW_SHADER";
