// GENERATED by tools/embed_shaders.py — do not edit.
// Source: shaders/seabed_web.vs
// Regenerate: python3 tools/embed_shaders.py
#pragma once

static const char* kSeabedVS = R"DW_SHADER(attribute vec3 vertexPosition;
uniform mat4 mvp;
varying vec3 vWorldPos;
void main() {
    vWorldPos = vertexPosition;
    gl_Position = mvp * vec4(vertexPosition, 1.0);
}
)DW_SHADER";
