// GENERATED by tools/embed_shaders.py — do not edit.
// Source: shaders/sky_desktop.vs
// Regenerate: python3 tools/embed_shaders.py
#pragma once

static const char* kSkyVS = R"DW_SHADER(#version 330
in vec3 vertexPosition;
uniform mat4 mvp;
out vec3 vDir;
void main() {
    vDir = vertexPosition;
    gl_Position = mvp * vec4(vertexPosition, 1.0);
}
)DW_SHADER";
