// GENERATED by tools/embed_shaders.py — do not edit.
// Source: shaders/water_desktop.vs
// Regenerate: python3 tools/embed_shaders.py
#pragma once

static const char* kWaterVS = R"DW_SHADER(#version 330
in vec3 vertexPosition;
uniform mat4 mvp;
uniform float uTime;
out vec3 vWorldPos;
out vec3 vNormalW;
out float vCrest;
vec3 waveHD(vec2 p, vec2 dir, float amp, float len, float t) {
    vec2 D = normalize(dir);
    float k = 6.2831853 / len;
    float s = sqrt(9.81 * k);
    float f = k * dot(D, p) - s * t;
    return vec3(amp * sin(f), D * (k * amp * cos(f)));
}
void main() {
    vec2 p = vertexPosition.xz;
    vec3 w1 = waveHD(p, vec2(0.85, 0.4), 0.08, 115.0, uTime);
    vec3 w2 = waveHD(p, vec2(-0.65, 0.76), 0.05, 61.0, uTime);
    float h = w1.x + w2.x;
    vec2 g = w1.yz + w2.yz;
    vNormalW = normalize(vec3(-g.x, 1.0, -g.y));
    vCrest = clamp(h / 0.13, -1.0, 1.0);
    vec3 wp = vertexPosition + vec3(0.0, h, 0.0);
    vWorldPos = wp;
    gl_Position = mvp * vec4(wp, 1.0);
}
)DW_SHADER";
